:app_id: 228632620521384
:secret: 819e0784baf56c08da01d1be397069ab
:api_key: 228632620521384
:base_url: http://growanavtree.com
:after_login_path: /dashboard/
:after_register_path: /dashboard/
:url_after_create: /dashboard/
:mailer_sender: ranger@growanavtree.com
