:app_id: 228632620521384
:secret: ---
:api_key: ---
:base_url: http://growanavtree.com
:after_login_path: /dashboard/
:after_register_path: /dashboard/
:url_after_create: /dashboard/
:mailer_sender: ranger@growanavtree.com
